# Generated by Django 3.1.6 on 2021-02-03 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('periodic_number', models.IntegerField()),
                ('type', models.CharField(choices=[('TEXT_ANSWER', 'TEXT_ANSWER'), ('ONE', 'ONE'), ('MANY', 'MANY')], default='TEXT_ANSWER', max_length=255)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.poll')),
            ],
        ),
    ]
