# Generated by Django 3.1.6 on 2021-02-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('ONE', 'ONE'), ('MANY', 'MANY')], default='TEXT', max_length=255),
        ),
    ]
