# Generated by Django 3.1.6 on 2021-02-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_auto_20210203_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.BooleanField(),
        ),
    ]
