# Generated by Django 3.1.6 on 2021-02-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0021_auto_20210204_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
