# Generated by Django 3.1.6 on 2021-02-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0022_answer_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='poll',
        ),
    ]
