# Generated by Django 3.1.6 on 2021-02-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0026_auto_20210204_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='text',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
